//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DataFim deve ser posterior a DataInicio.
        /// </summary>
        internal static string DataFimDeveSerAposDataInicio {
            get {
                return ResourceManager.GetString("DataFimDeveSerAposDataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email já existe.
        /// </summary>
        internal static string EmailJaExiste {
            get {
                return ResourceManager.GetString("EmailJaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email ou senha inválidos.
        /// </summary>
        internal static string EmailOuSenhaInvalidos {
            get {
                return ResourceManager.GetString("EmailOuSenhaInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Item não encontrado.
        /// </summary>
        internal static string ItemNaoEncontrado {
            get {
                return ResourceManager.GetString("ItemNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jogo já cadastrado na biblioteca do usuário.
        /// </summary>
        internal static string JogoJaCadastradoNaBiblioteca {
            get {
                return ResourceManager.GetString("JogoJaCadastradoNaBiblioteca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jogo não encontrado.
        /// </summary>
        internal static string JogoInativo {
            get {
                return ResourceManager.GetString("JogoInativo", resourceCulture);
            }
        }

        internal static string JogoNaoEncontrado {
            get {
                return ResourceManager.GetString("JogoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Promoção inválida ou expirada.
        /// </summary>
        internal static string PromocaoInvalidaOuExpirada {
            get {
                return ResourceManager.GetString("PromocaoInvalidaOuExpirada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Promoção não encontrada.
        /// </summary>
        internal static string PromocaoNaoEncontrada {
            get {
                return ResourceManager.GetString("PromocaoNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não encontrado.
        /// </summary>
        internal static string UsuarioNaoEncontrado {
            get {
                return ResourceManager.GetString("UsuarioNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário sem permissão.
        /// </summary>
        internal static string UsuarioSemPermissao {
            get {
                return ResourceManager.GetString("UsuarioSemPermissao", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formato de e-mail inválido.
        /// </summary>
        internal static string EmailFormatoInvalido {
            get {
                return ResourceManager.GetString("EmailFormatoInvalido", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve ter no mínimo 8 caracteres, contendo letras, números e caracteres especiais.
        /// </summary>
        internal static string SenhaInsegura {
            get {
                return ResourceManager.GetString("SenhaInsegura", resourceCulture);
            }
        }

        internal static string TokenRecuperacaoEnviado {
            get {
                return ResourceManager.GetString("TokenRecuperacaoEnviado", resourceCulture);
            }
        }

        internal static string TokenInvalidoOuExpirado {
            get {
                return ResourceManager.GetString("TokenInvalidoOuExpirado", resourceCulture);
            }
        }

        internal static string SenhaAlteradaComSucesso {
            get {
                return ResourceManager.GetString("SenhaAlteradaComSucesso", resourceCulture);
            }
        }
    }
}
